# Generated by Django 4.0.1 on 2022-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname_empl', models.CharField(max_length=50)),
                ('Name_empl', models.CharField(max_length=50)),
                ('Post', models.CharField(default='MANAGER', max_length=50, verbose_name=(('MANAGER', 'Manager'), ('FINANCE DIRECTOR', 'Finance Director'), ('PRODUCT DIRECTOR', 'Product Director'), ('IT DIRECTOR', 'IT Director'), ('GENERAL DIRECTOR', 'General Director')))),
                ('Date_employment', models.DateField(auto_now_add=True)),
                ('Salary', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
