# Generated by Django 4.0.1 on 2022-09-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Surname_empl',
            new_name='Surename_empl',
        ),
    ]
