# Generated by Django 4.0.1 on 2022-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_surname_empl_employee_surename_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Post',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('FINANCE DIRECTOR', 'Finance Director'), ('PRODUCT DIRECTOR', 'Product Director'), ('IT DIRECTOR', 'IT Director'), ('GENERAL DIRECTOR', 'General Director')], default='MANAGER', max_length=50),
        ),
    ]
