# Generated by Django 4.0.1 on 2022-09-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boss_alter_employee_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.boss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boss',
            name='Post_Boss',
            field=models.CharField(choices=[('Finance Director', 'Finance Director'), ('Product Director', 'Product Director'), ('IT Director', 'IT Director'), ('General Director', 'General Director')], max_length=50),
        ),
    ]
